/*******************************************************************************
 * Copyright (c) 2000, 2022 IBM Corporation and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.jdt.internal.compiler.parser;

/*An interface that contains static declarations for some basic information
 about the parser such as the number of rules in the grammar, the starting state, etc...*/
public interface ParserBasicInformation {

	public final static int
	// BEGIN_AUTOGENERATED_REGION

					ERROR_SYMBOL = 141,
					MAX_NAME_LENGTH = 53,
					NUM_STATES = 1240,

					NT_OFFSET = 141,
					SCOPE_UBOUND = 322,
					SCOPE_SIZE = 323,
					LA_STATE_OFFSET = 18362,
					MAX_LA = 1,
					NUM_RULES = 947,
					NUM_TERMINALS = 141,
					NUM_NON_TERMINALS = 437,
					NUM_SYMBOLS = 578,
					START_STATE = 1008,
					EOFT_SYMBOL = 65,
					EOLT_SYMBOL = 65,
					ACCEPT_ACTION = 18361,
					ERROR_ACTION = 18362;
}
