/*******************************************************************************
 * Copyright (c) 2000, 2022 IBM Corporation and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.jdt.internal.compiler.parser;

/*An interface that contains static declarations for some basic information
 about the parser such as the number of rules in the grammar, the starting state, etc...*/
public interface ParserBasicInformation {

	public final static int
	// BEGIN_AUTOGENERATED_REGION

					ERROR_SYMBOL = 142,
					MAX_NAME_LENGTH = 53,
					NUM_STATES = 1249,

					NT_OFFSET = 142,
					SCOPE_UBOUND = 323,
					SCOPE_SIZE = 324,
					LA_STATE_OFFSET = 18835,
					MAX_LA = 1,
					NUM_RULES = 953,
					NUM_TERMINALS = 142,
					NUM_NON_TERMINALS = 438,
					NUM_SYMBOLS = 580,
					START_STATE = 1014,
					EOFT_SYMBOL = 66,
					EOLT_SYMBOL = 66,
					ACCEPT_ACTION = 18834,
					ERROR_ACTION = 18835;
}
