name: Continuous Integration
concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Set up JDKs ☕
      uses: actions/setup-java@v3
      with:
        java-version: |
          17
          21
        mvn-toolchain-id: |
          JavaSE-17
          JavaSE-21
        distribution: 'temurin'
    - name: Set up Maven
      uses: stCarolas/setup-maven@07fbbe97d97ef44336b7382563d66743297e442f # v4.5
      with:
        maven-version: 3.9.3
    - name: Build org.eclipse.jdt.core.compiler.batch with Maven 🏗️
      run: |
        mvn clean install --batch-mode -f org.eclipse.jdt.core.compiler.batch -DlocalEcjVersion=99.99
        #mvn -U clean verify --batch-mode --fail-at-end -Ptest-on-javase-20 -Pbree-libs -Papi-check -Djava.io.tmpdir=$WORKSPACE/tmp -Dproject.build.sourceEncoding=UTF-8 -Dtycho.surefire.argLine="--add-modules ALL-SYSTEM -Dcompliance=1.8,11,17,20 -Djdt.performance.asserts=disabled" -Dcbi-ecj-version=99.99
    - name: Build org.eclipse.jdt.core with Maven 🏗️
      run: |
        mvn clean install --batch-mode -f org.eclipse.jdt.core -DlocalEcjVersion=99.99
        #mvn -U clean verify --batch-mode --fail-at-end -Ptest-on-javase-20 -Pbree-libs -Papi-check -Djava.io.tmpdir=$WORKSPACE/tmp -Dproject.build.sourceEncoding=UTF-8 -Dtycho.surefire.argLine="--add-modules ALL-SYSTEM -Dcompliance=1.8,11,17,20 -Djdt.performance.asserts=disabled" -Dcbi-ecj-version=99.99
    - name: Upload plugins as artifact
      uses: actions/upload-artifact@v3
      with:
        name: plugins
        path: |
          org.eclipse.jdt.core.compiler.batch/target/org.eclipse.jdt.core.compiler.batch-3.36.0-SNAPSHOT.jar
          org.eclipse.jdt.core/target/org.eclipse.jdt.core-3.36.0-SNAPSHOT.jar
